name: Assign Milestone

on:
  pull_request_target:
    types: [opened]

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Assign Milestone
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
<<<<<<< HEAD
          go-version: 1.22.5
=======
          go-version: 1.22.5
>>>>>>> c60a5ea6b3 ([release-19.0] Upgrade the Golang version to `go1.22.5` (#16322))

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assign Milestone
        run: |
          gh pr edit ${{ github.event.number }} --milestone "v$(sed -n 's/.*versionName.*\"\([[:digit:]\.]*\).*\"/\1/p' ./go/vt/servenv/version.go)"
