name: check_make_sizegen
on: [push, pull_request]
jobs:

  build:
    name: Check Make Sizegen
    runs-on:
      group: vitess-ubuntu20
    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true

    - name: Tune the OS
      run: |
        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make unzip g++ etcd curl git wget
        sudo service etcd stop
        go mod download
        go install golang.org/x/tools/cmd/goimports@latest

    - name: Run make minimaltools
      run: |
        make minimaltools

    - name: check_make_sizegen
      run: |
        tools/check_make_sizegen.sh

