name: docker_test_cluster_10
on: [push, pull_request]
permissions: read-all
env:
  GOPRIVATE: github.com/slackhq/vitess-addons
  GH_ACCESS_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
jobs:

  build:
    name: Docker Test Cluster 10
    runs-on:
      group: vitess-ubuntu20

    steps:
    - name: Skip CI
      run: |
        if [[ "${{contains( github.event.pull_request.labels.*.name, 'Skip CI')}}" == "true" ]]; then
          echo "skipping CI due to the 'Skip CI' label"
          exit 1
        fi

    - name: Check if workflow needs to be skipped
      id: skip-workflow
      run: |
        skip='false'
        echo Skip $skip
        echo "skip-workflow=${skip}" >> $GITHUB_OUTPUT

    - name: Check out code
      if: steps.skip-workflow.outputs.skip-workflow == 'false'
      uses: actions/checkout@v4

    - name: Check for changes in relevant files
      if: steps.skip-workflow.outputs.skip-workflow == 'false'
      uses: dorny/paths-filter@v3.0.1
      id: changes
      with:
        token: ''
        filters: |
          end_to_end:
            - 'go/**/*.go'
            - 'test.go'
            - 'Makefile'
            - 'build.env'
            - 'go.sum'
            - 'go.mod'
            - 'proto/*.proto'
            - 'tools/**'
            - 'config/**'
            - 'bootstrap.sh'
            - 'docker/**'
            - '.github/workflows/docker_test_cluster_10.yml'

    - name: Set up Go
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.7

    - name: Setup github.com/slackhq/vitess-addons access token
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
      run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

    - name: Tune the OS
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
      run: |
        echo "value: " ${{steps.skip-workflow.outputs.skip-workflow}}
        sudo sysctl -w net.ipv4.ip_local_port_range="22768 65535"

    - name: Run tests which require docker - 1
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
      run: |
        go run test.go -docker=true --follow -shard 10
